on: 
  schedule:  
    - cron:  '30 8,20 * * *'
    
name: Web scraping trains

jobs:
  render:
    name: Web scraping trains
    runs-on: macos-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      # Install R
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.1.3'

      # Set-up R
      - name: Restore packages
        shell: Rscript {0}
        run: |
          if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
          renv::restore()

      - name: Scrape the data
        run: Rscript scrap.R

      - name: Commit results
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add -A
          git commit -m 'Add data'
          git push origin main